version: "3.9"
services:
  app:
    hostname: app
    build: .
    volumes:
      - ./src:/code/src
    ports:
      - 8080:8080
    depends_on:
      - "db"

  db:
    image: postgres:14-alpine
    hostname: db
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=invitease
      - POSTGRES_DB=invitease
    ports:
      - 5432:5432
    volumes:
      - ./db_init/:/docker-entrypoint-initdb.d/
      - pg_data:/var/lib/postgresql/data
  keycloak:
    image: bitnami/keycloak:15.0.2
    hostname: keycloak
    ports:
      - "8081:8080"
    depends_on:
      - db
    environment:
      - KEYCLOAK_DATABASE_HOST=db
      - KEYCLOAK_DATABASE_USER=invitease
      - KEYCLOAK_DATABASE_PASSWORD=password
      - KEYCLOAK_DATABASE_NAME=keycloak
volumes:
  pg_data:        
