version: "3.9"
services:
  app:
    hostname: app
    build: .
    volumes:
      - ./src:/code/src
    networks:
      - web
    depends_on:
      - "db"
      - "keycloak"
    environment:
       IVT_OPENID_DISCOVERY_URL: 'http://keycloak:8080/auth/realms/master/.well-known/openid-configuration'
       IVT_OPENID_DISCOVERY_EXTERNAL_URL: 'http://keycloak.localhost/auth/realms/master/.well-known/openid-configuration'
       IVT_ENABLE_AUTH: 'true'
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.invitease.rule=Host(`invitease.localhost`)"
    - "traefik.http.routers.invitease.entrypoints=web"
    - "traefik.docker.network=web"
    - "traefik.http.services.invitease.loadbalancer.server.port=8090"

  db:
    image: postgres:14-alpine
    hostname: db
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=invitease
      - POSTGRES_DB=invitease
    ports:
      - 5432:5432
    networks:
      - web
    volumes:
      - ./db_init/:/docker-entrypoint-initdb.d/
      - pg_data:/var/lib/postgresql/data

  keycloak:
    image: bitnami/keycloak:15.1.0
    hostname: keycloak
    networks:
      - web
    depends_on:
      - db
    environment:
      - KEYCLOAK_ADMIN_USER=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_DATABASE_HOST=db
      - KEYCLOAK_DATABASE_USER=invitease
      - KEYCLOAK_DATABASE_PASSWORD=password
      - KEYCLOAK_DATABASE_NAME=keycloak
      - KEYCLOAK_FRONTEND_URL=keycloak.localhost
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.keycloak.rule=Host(`keycloak.localhost`)"
      - "traefik.http.routers.keycloak.entrypoints=web"
      - "traefik.docker.network=web"
      - "traefik.http.services.keycloak.loadbalancer.server.port=8080"


  traefik:
    image: traefik:v2.5.4
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    depends_on:
      - "app"
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`dash.localhost`)"
      - "traefik.http.routers.dashboard.entrypoints=web"
      - "traefik.http.routers.dashboard.service=api@internal"
    ports:
      - "80:80"
    networks:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  web:
    driver: bridge

volumes:
  pg_data:        
