version: "3.9"
services:
  app:
    hostname: app
    build: .
    restart: unless-stopped
    volumes:
      - ./src:/code/src
    networks:
      - web
    depends_on:
      - "db"
      - "keycloak"
    environment:
       IVT_OPENID_DISCOVERY_URL: 'http://keycloak:8080/auth/realms/master/.well-known/openid-configuration'
       IVT_OPENID_DISCOVERY_EXTERNAL_URL: 'http://keycloak.localhost/auth/realms/master/.well-known/openid-configuration'
      #  IVT_ENABLE_AUTH: 'true'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.invitease.rule=Host(`invitease.localhost`)"
      - "traefik.http.routers.invitease.entrypoints=web"
      - "traefik.docker.network=web"
      - "traefik.http.services.invitease.loadbalancer.server.port=8090"

  dbmanager:
    image: dpage/pgadmin4
    hostname: dbmanager
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=invitease@mmm.org.il
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=8084
    volumes:
      - ./db_init/servers.json:/pgadmin4/servers.json
    depends_on:
      - db
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dbadmin.rule=Host(`dbadmin.localhost`)"
      - "traefik.http.routers.dbadmin.entrypoints=web"
      - "traefik.docker.network=web"
      - "traefik.http.services.dbadmin.loadbalancer.server.port=8084"

  db:
    image: postgres:14-alpine
    hostname: db
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=invitease
      - POSTGRES_DB=invitease
    networks:
      - web
    volumes:
      - ./db_init/baseline.sql:/docker-entrypoint-initdb.d/baseline.sql
      - pg_data:/var/lib/postgresql/data

  keycloak:
    image: bitnami/keycloak:15.1.0
    hostname: keycloak
    restart: unless-stopped
    networks:
      - web
    depends_on:
      - db
    environment:
      - KEYCLOAK_ADMIN_USER=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_DATABASE_HOST=db
      - KEYCLOAK_DATABASE_USER=invitease
      - KEYCLOAK_DATABASE_PASSWORD=password
      - KEYCLOAK_DATABASE_NAME=keycloak
      - KEYCLOAK_FRONTEND_URL=keycloak.localhost
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.keycloak.rule=Host(`keycloak.localhost`)"
      - "traefik.http.routers.keycloak.entrypoints=web"
      - "traefik.docker.network=web"
      - "traefik.http.services.keycloak.loadbalancer.server.port=8080"


  traefik:
    image: traefik:v2.5.4
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    depends_on:
      - "app"
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`dash.localhost`)"
      - "traefik.http.routers.dashboard.entrypoints=web"
      - "traefik.http.routers.dashboard.service=api@internal"
    ports:
      - "80:80"
    networks:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  web:
    driver: bridge

volumes:
  pg_data:        
